# This is a basic workflow to help you get started with Actions

name: CI

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 12.x

      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-

      - name: yarn install
        run: yarn install --immutable

      - name: sort-package-json
        run: yarn sort-package-json --check

      - name: TypeScript
        run: yarn typescript:check

      - name: ESLint
        run: yarn lint

      - name: Stylelint
        run: yarn stylelint

      - name: Tests
        run: yarn test

      - name: Chroma
        uses: chromaui/action@v1
        with:
          exitOnceUploaded: true
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: main
